
GET https://en.wikipedia.org/wiki/Donald_Trump


####

GET https://upload.wikimedia.org/wikipedia/en/thumb/2/28/TrumpGlobe_Sept287.png


####

GET https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Donald_Trump_August_19%2C_2015_%28cropped%29.jpg/220px-Donald_Trump_August_19%2C_2015_%28cropped%29.jpg


####

GET http://localhost:8888/
####

GET http://localhost:8888/goodbye

####

GET http://localhost:8888/age

####

POST http://localhost:8888/age
Content-Type: text/plain

foo


####   Content-Type: application/json


POST http://localhost:8888/people
Content-Type: application/json

{
  "label":"middle",
  "name":"James"
}

####


POST http://localhost:8888/people
Content-Type: application/json

{"employees":[
    {"firstName":"John", "lastName":"Doe"},
    {"firstName":"Anna", "lastName":"Smith"},
    {"firstName":"Peter", "lastName":"Jones"}
]}

####



GET http://www.timeapi.org/utc/now

####

GET http://date.jsontest.com


####

GET http://api.espn.com/v1/sports/baseball/mlb/events

####

GET https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20fantasysports.games%20where%20game_key%3D%22238%22&diagnostics=true

####

GET http://127.0.0.1:8888/countries

###

POST http://127.0.0.1:8888/age

10

####

POST http://127.0.0.1:8888/query

SELECT * FROM country;

